server:
  port: 8081
  servlet:
    # 修改项目的context-path
    context-path: /study-Demo1/
# 异常处理配置
spring:
  resources:
   add-mappings: false
  # 配置mysql 读写分类 ,配置多个数据源
  datasource:
    database1:
      jdbc-url: jdbc:mysql://localhost:3306/database1?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    database2:
      jdbc-url: jdbc:mysql://localhost:3306/database2?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
# 使用druid
    type: com.alibaba.druid.pool.DruidDataSource
    #配置mongodb
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
# 配置mongodb
# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
#spring boot静态文件缓存配置

